/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Cine;

import Cine.Salas.SalasCine;

/**
 *
 * @author Daniel
 */
public class MenuAdmin extends javax.swing.JFrame {
    SalasCine salas = new SalasCine();
    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LblUser = new javax.swing.JLabel();
        BtnSalas = new javax.swing.JButton();
        BtnPeliculas = new javax.swing.JButton();
        BtnEditarP = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Bienvenido ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(38, 22, 90, 30);
        getContentPane().add(LblUser);
        LblUser.setBounds(290, 20, 100, 30);

        BtnSalas.setText("Salas de Cine");
        BtnSalas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSalasMouseClicked(evt);
            }
        });
        BtnSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalasActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalas);
        BtnSalas.setBounds(130, 100, 110, 30);

        BtnPeliculas.setText("Peliculas");
        BtnPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPeliculasActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPeliculas);
        BtnPeliculas.setBounds(130, 150, 110, 30);

        BtnEditarP.setText("Editar Perfil");
        getContentPane().add(BtnEditarP);
        BtnEditarP.setBounds(130, 200, 110, 30);

        BtnSalir.setText("Salir");
        BtnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSalirMouseClicked(evt);
            }
        });
        getContentPane().add(BtnSalir);
        BtnSalir.setBounds(310, 260, 53, 23);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-416)/2, (screenSize.height-339)/2, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPeliculasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPeliculasActionPerformed

    private void BtnSalasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSalasMouseClicked
        this.salas.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSalasMouseClicked

    private void BtnSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSalasActionPerformed

    private void BtnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSalirMouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEditarP;
    private javax.swing.JButton BtnPeliculas;
    private javax.swing.JButton BtnSalas;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JLabel LblUser;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
