/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Cine;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class Register extends javax.swing.JFrame {
    ArrayList<Users> Info = new ArrayList<>();
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtUsername = new javax.swing.JTextField();
        TxtFullname = new javax.swing.JTextField();
        BtnRegistrar = new javax.swing.JButton();
        TxtPassword = new javax.swing.JPasswordField();
        TxtRPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Registro de Usuarios");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 20, 160, 30);

        jLabel2.setText("Nombre de Usuario:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 100, 120, 20);

        jLabel3.setText("Nombre completo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 140, 120, 20);

        jLabel4.setText("Contraseña:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 180, 120, 20);

        jLabel5.setText("Repita contraseña:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 220, 120, 20);

        TxtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(TxtUsername);
        TxtUsername.setBounds(180, 100, 130, 20);
        getContentPane().add(TxtFullname);
        TxtFullname.setBounds(180, 140, 130, 20);

        BtnRegistrar.setText("Registrar");
        BtnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRegistrarMouseClicked(evt);
            }
        });
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegistrar);
        BtnRegistrar.setBounds(130, 280, 90, 23);
        getContentPane().add(TxtPassword);
        TxtPassword.setBounds(180, 180, 100, 20);
        getContentPane().add(TxtRPassword);
        TxtRPassword.setBounds(180, 220, 100, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-382)/2, (screenSize.height-423)/2, 382, 423);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsernameActionPerformed

    private void BtnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegistrarMouseClicked
        // TODO add your handling code here:
        if(buscarInfo(TxtUsername.getText()))
            JOptionPane.showMessageDialog(this, "Ya existe un registro con ese nombre de usuario!",
            "Usuarios",JOptionPane.WARNING_MESSAGE);
        else if(this.TxtUsername.getText().isEmpty())
        JOptionPane.showMessageDialog(this, "El Nombre de usuario esta vacio!",
            "Información necesaria",JOptionPane.WARNING_MESSAGE);
        else if(this.TxtFullname.getText().isEmpty())
        JOptionPane.showMessageDialog(this, "El Nombre completo esta vacio!",
            "Información necesaria",JOptionPane.WARNING_MESSAGE);
        else if(this.TxtPassword.getText().isEmpty())
        JOptionPane.showMessageDialog(this, "La contraseña esta vacia!",
            "Información necesaria",JOptionPane.WARNING_MESSAGE);
        else if(!(this.TxtRPassword.getText().equals(this.TxtPassword.getText())))
        JOptionPane.showMessageDialog(this, "Contraseñas diferentes!",
            "Información necesaria",JOptionPane.WARNING_MESSAGE);
        else{
            this.Info.add(new Users(this.TxtUsername.getText(),this.TxtFullname.getText(),this.TxtPassword.getText()));
            JOptionPane.showMessageDialog(this,"Información guardada con éxito.","Registro",
                JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        }
    }//GEN-LAST:event_BtnRegistrarMouseClicked

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    public boolean validarInfo(String name,String pass){
        for(int i=0;i<Info.size();i++){
            if(name.equals(Info.get(i).getUsername())&&
                    pass.equals(Info.get(i).getPassword())){
                return true;
            }
        }
        return false;
    }
    
    private boolean buscarInfo(String username){
        for(int i=0;i<Info.size();i++){
            if(Info.get(i).getUsername().equals(username))
                return true;
        }
        return false;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JTextField TxtFullname;
    private javax.swing.JPasswordField TxtPassword;
    private javax.swing.JPasswordField TxtRPassword;
    private javax.swing.JTextField TxtUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
