/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Cine;

import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class User_Login extends javax.swing.JFrame {

    Register Registro = new Register();
    MenuAdmin menu = new MenuAdmin();
    
    public User_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloSesión = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        TxtUser = new javax.swing.JTextField();
        pass = new javax.swing.JLabel();
        TxtPasswordU = new javax.swing.JPasswordField();
        BtnIngresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnRegistrarse = new javax.swing.JButton();
        LblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Usuarios");
        setBackground(new java.awt.Color(51, 51, 255));
        setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        setForeground(new java.awt.Color(255, 153, 0));
        getContentPane().setLayout(null);

        TituloSesión.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TituloSesión.setForeground(new java.awt.Color(0, 0, 153));
        TituloSesión.setText("Iniciar sesión");
        TituloSesión.setToolTipText("");
        getContentPane().add(TituloSesión);
        TituloSesión.setBounds(100, 50, 110, 23);

        usuario.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        usuario.setForeground(new java.awt.Color(102, 102, 0));
        usuario.setText("Usuario:");
        getContentPane().add(usuario);
        usuario.setBounds(50, 90, 60, 30);

        TxtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUserActionPerformed(evt);
            }
        });
        getContentPane().add(TxtUser);
        TxtUser.setBounds(80, 120, 140, 30);

        pass.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        pass.setForeground(new java.awt.Color(102, 102, 0));
        pass.setText("Password:");
        getContentPane().add(pass);
        pass.setBounds(50, 160, 70, 20);
        getContentPane().add(TxtPasswordU);
        TxtPasswordU.setBounds(80, 180, 140, 30);

        BtnIngresar.setText("Ingresar");
        BtnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnIngresarMouseClicked(evt);
            }
        });
        getContentPane().add(BtnIngresar);
        BtnIngresar.setBounds(90, 230, 80, 23);
        BtnIngresar.getAccessibleContext().setAccessibleName("BtnIngresar");

        jLabel1.setText("Nuevo Usuario!");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 200, 90, 20);

        BtnRegistrarse.setText("Registrarse!");
        BtnRegistrarse.setActionCommand("");
        BtnRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRegistrarseMouseClicked(evt);
            }
        });
        getContentPane().add(BtnRegistrarse);
        BtnRegistrarse.setBounds(290, 230, 100, 23);
        BtnRegistrarse.getAccessibleContext().setAccessibleName("BtnRegistrarse");

        getContentPane().add(LblFondo);
        LblFondo.setBounds(0, 10, 430, 320);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-458)/2, (screenSize.height-370)/2, 458, 370);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUserActionPerformed
     
    }//GEN-LAST:event_TxtUserActionPerformed

    private void BtnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIngresarMouseClicked
        // TODO add your handling code here:
        if(Registro.validarInfo(this.TxtUser.getText(), this.TxtPasswordU.getText())){
            this.menu.setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(this,"La información no existe","Información inválida",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnIngresarMouseClicked

    private void BtnRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegistrarseMouseClicked
        Registro.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRegistrarseMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
    }//GEN-LAST:event_jLabel1MouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JButton BtnRegistrarse;
    private javax.swing.JLabel LblFondo;
    private javax.swing.JLabel TituloSesión;
    private javax.swing.JPasswordField TxtPasswordU;
    private javax.swing.JTextField TxtUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel pass;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
