/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Cine.Salas;

import Cine.MenuAdmin;

/**
 *
 * @author Daniel
 */
public class SalasCine extends javax.swing.JFrame {
    CrearSala crear = new CrearSala();
    MenuAdmin menu2 = new MenuAdmin();
    /**
     * Creates new form SalasCine
     */
    public SalasCine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BtnCrearS = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BtnMenuB = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Salas de Cine");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Salas de Cine");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 10, 130, 30);

        BtnCrearS.setText("Crear Sala");
        BtnCrearS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCrearSMouseClicked(evt);
            }
        });
        BtnCrearS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearSActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCrearS);
        BtnCrearS.setBounds(30, 310, 90, 30);

        jButton2.setText("jButton2");
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 310, 90, 30);

        BtnMenuB.setText("Menu Administrador");
        BtnMenuB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMenuBMouseClicked(evt);
            }
        });
        getContentPane().add(BtnMenuB);
        BtnMenuB.setBounds(300, 310, 130, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(30, 300, 400, 30);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(30, 50, 400, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-492)/2, (screenSize.height-413)/2, 492, 413);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCrearSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearSActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCrearSActionPerformed

    private void BtnCrearSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCrearSMouseClicked
        this.crear.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCrearSMouseClicked

    private void BtnMenuBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMenuBMouseClicked
        this.menu2.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMenuBMouseClicked

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrearS;
    private javax.swing.JButton BtnMenuB;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
